# This is a basic workflow to help you get started with Actions

name: CallAnotherWFOFTESTREPO1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main1 ]
  pull_request:
    branches: [ main1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: 'Bearer ${{ secrets.PAT_TOKEN }}'" \
          --data '{"event_type": "sample_push", "client_payload": { "version": "1.2.3"}}' \
          https://api.github.com/repos/PrashantIG1/testrepo1/dispatches
          
      - name: Run a multi-line script2
        run: | 
          echo Add other actions to build,
          echo test, and deploy your project.
          echo 'Bearer ${{ secrets.PAT_TOKEN1 }}'
          curl --location --request POST 'https://api.github.com/repos/PrashantIG1/testrepo1/dispatches' \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Authorization: 'Bearer ${{ secrets.PAT_TOKEN }}'" \
          --header "Content-Type: application/json" \
          --data-raw '{"event_type": "sample_push1","client_payload": { "version": "1.2.3"} }'
